/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  StrategyRegistry,
  StrategyRegistryInterface,
} from "../../contracts/StrategyRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_gov",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "gov",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "id",
            type: "bytes32",
          },
          {
            internalType: "uint8",
            name: "classId",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "enabled",
            type: "bool",
          },
        ],
        internalType: "struct StrategyMeta",
        name: "meta",
        type: "tuple",
      },
    ],
    name: "registerStrategy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "setStrategyEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "strategies",
    outputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "classId",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161035738038061035783398101604081905261002f91610054565b600180546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6102c4806100936000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806304868df01461005157806312d43a51146100665780633ff34eb914610096578063c98fd0a4146100e8575b600080fd5b61006461005f3660046101e4565b6100fb565b005b600154610079906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b6100c96100a4366004610214565b6000602081905290815260409020805460019091015460ff8082169161010090041683565b6040805193845260ff909216602084015215159082015260600161008d565b6100646100f636600461022d565b61016e565b6001546001600160a01b031633146101445760405162461bcd60e51b81526020600482015260076024820152662727aa2fa3a7ab60c91b60448201526064015b60405180910390fd5b60009182526020829052604090912060010180549115156101000261ff0019909216919091179055565b6001546001600160a01b031633146101b25760405162461bcd60e51b81526020600482015260076024820152662727aa2fa3a7ab60c91b604482015260640161013b565b8035600090815260208190526040902081906101ce8282610245565b505050565b80151581146101e157600080fd5b50565b600080604083850312156101f757600080fd5b823591506020830135610209816101d3565b809150509250929050565b60006020828403121561022657600080fd5b5035919050565b60006060828403121561023f57600080fd5b50919050565b8135815560018101602083013560ff811680821461026257600080fd5b825491506040850135610274816101d3565b61ffff19929092161790151560081b61ff0016179055505056fea26469706673582212208c0ba3466aefdf9344ba23fa3a7663b4f96a8ac0a30fb328d748c8cfa728eb0c64736f6c63430008140033";

type StrategyRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StrategyRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StrategyRegistry__factory extends ContractFactory {
  constructor(...args: StrategyRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _gov: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_gov, overrides || {});
  }
  override deploy(
    _gov: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_gov, overrides || {}) as Promise<
      StrategyRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): StrategyRegistry__factory {
    return super.connect(runner) as StrategyRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StrategyRegistryInterface {
    return new Interface(_abi) as StrategyRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): StrategyRegistry {
    return new Contract(address, _abi, runner) as unknown as StrategyRegistry;
  }
}
