/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HydraVaultFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createVault" | "policyStore" | "riskGuardian"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createVault",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "policyStore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskGuardian",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskGuardian",
    data: BytesLike
  ): Result;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [vault: AddressLike, vaultId: BytesLike];
  export type OutputTuple = [vault: string, vaultId: string];
  export interface OutputObject {
    vault: string;
    vaultId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HydraVaultFactory extends BaseContract {
  connect(runner?: ContractRunner | null): HydraVaultFactory;
  waitForDeployment(): Promise<this>;

  interface: HydraVaultFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createVault: TypedContractMethod<
    [vaultId: BytesLike],
    [string],
    "nonpayable"
  >;

  policyStore: TypedContractMethod<[], [string], "view">;

  riskGuardian: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<[vaultId: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "policyStore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "riskGuardian"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;

  filters: {
    "VaultCreated(address,bytes32)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
  };
}
