/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type StrategyWeightStruct = { strategyId: BytesLike; bps: BigNumberish };

export type StrategyWeightStructOutput = [strategyId: string, bps: bigint] & {
  strategyId: string;
  bps: bigint;
};

export type MCPPolicyStruct = {
  policyId: BytesLike;
  weights: StrategyWeightStruct[];
  timestamp: BigNumberish;
  validUntil: BigNumberish;
};

export type MCPPolicyStructOutput = [
  policyId: string,
  weights: StrategyWeightStructOutput[],
  timestamp: bigint,
  validUntil: bigint
] & {
  policyId: string;
  weights: StrategyWeightStructOutput[];
  timestamp: bigint;
  validUntil: bigint;
};

export interface MCPOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "gov"
      | "policyStore"
      | "setSigner"
      | "signers"
      | "submitPolicy"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gov", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policyStore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSigner",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPolicy",
    values: [AddressLike, MCPPolicyStruct, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "gov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSigner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitPolicy",
    data: BytesLike
  ): Result;
}

export interface MCPOracle extends BaseContract {
  connect(runner?: ContractRunner | null): MCPOracle;
  waitForDeployment(): Promise<this>;

  interface: MCPOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gov: TypedContractMethod<[], [string], "view">;

  policyStore: TypedContractMethod<[], [string], "view">;

  setSigner: TypedContractMethod<
    [signer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  signers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  submitPolicy: TypedContractMethod<
    [vault: AddressLike, policy_: MCPPolicyStruct, arg2: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gov"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyStore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSigner"
  ): TypedContractMethod<
    [signer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitPolicy"
  ): TypedContractMethod<
    [vault: AddressLike, policy_: MCPPolicyStruct, arg2: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
