/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type StrategyWeightStruct = { strategyId: BytesLike; bps: BigNumberish };

export type StrategyWeightStructOutput = [strategyId: string, bps: bigint] & {
  strategyId: string;
  bps: bigint;
};

export type MCPPolicyStruct = {
  policyId: BytesLike;
  weights: StrategyWeightStruct[];
  timestamp: BigNumberish;
  validUntil: BigNumberish;
};

export type MCPPolicyStructOutput = [
  policyId: string,
  weights: StrategyWeightStructOutput[],
  timestamp: bigint,
  validUntil: bigint
] & {
  policyId: string;
  weights: StrategyWeightStructOutput[];
  timestamp: bigint;
  validUntil: bigint;
};

export interface MCPPolicyStoreInterface extends Interface {
  getFunction(
    nameOrSignature: "oracle" | "policy" | "setPolicy"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "policy", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setPolicy",
    values: [AddressLike, MCPPolicyStruct]
  ): string;

  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPolicy", data: BytesLike): Result;
}

export interface MCPPolicyStore extends BaseContract {
  connect(runner?: ContractRunner | null): MCPPolicyStore;
  waitForDeployment(): Promise<this>;

  interface: MCPPolicyStoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  oracle: TypedContractMethod<[], [string], "view">;

  policy: TypedContractMethod<
    [vault: AddressLike],
    [MCPPolicyStructOutput],
    "view"
  >;

  setPolicy: TypedContractMethod<
    [vault: AddressLike, policy_: MCPPolicyStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policy"
  ): TypedContractMethod<[vault: AddressLike], [MCPPolicyStructOutput], "view">;
  getFunction(
    nameOrSignature: "setPolicy"
  ): TypedContractMethod<
    [vault: AddressLike, policy_: MCPPolicyStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
