/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PerformanceSnapshotStruct = {
  vaultId: BytesLike;
  timestamp: BigNumberish;
  dailyReturnBps: BigNumberish;
  nav: BigNumberish;
};

export type PerformanceSnapshotStructOutput = [
  vaultId: string,
  timestamp: bigint,
  dailyReturnBps: bigint,
  nav: bigint
] & { vaultId: string; timestamp: bigint; dailyReturnBps: bigint; nav: bigint };

export interface PerformanceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "gov"
      | "lastSnapshot"
      | "reporters"
      | "setReporter"
      | "submitSnapshot"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gov", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastSnapshot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reporters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReporter",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSnapshot",
    values: [PerformanceSnapshotStruct, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "gov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reporters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSnapshot",
    data: BytesLike
  ): Result;
}

export interface PerformanceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PerformanceOracle;
  waitForDeployment(): Promise<this>;

  interface: PerformanceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gov: TypedContractMethod<[], [string], "view">;

  lastSnapshot: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        vaultId: string;
        timestamp: bigint;
        dailyReturnBps: bigint;
        nav: bigint;
      }
    ],
    "view"
  >;

  reporters: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setReporter: TypedContractMethod<
    [reporter: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  submitSnapshot: TypedContractMethod<
    [snap: PerformanceSnapshotStruct, arg1: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gov"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastSnapshot"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        vaultId: string;
        timestamp: bigint;
        dailyReturnBps: bigint;
        nav: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reporters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setReporter"
  ): TypedContractMethod<
    [reporter: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitSnapshot"
  ): TypedContractMethod<
    [snap: PerformanceSnapshotStruct, arg1: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
