/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type RiskLimitsStruct = {
  maxLeverageBps: BigNumberish;
  maxDrawdownBps: BigNumberish;
  maxSingleAssetExposureBps: BigNumberish;
};

export type RiskLimitsStructOutput = [
  maxLeverageBps: bigint,
  maxDrawdownBps: bigint,
  maxSingleAssetExposureBps: bigint
] & {
  maxLeverageBps: bigint;
  maxDrawdownBps: bigint;
  maxSingleAssetExposureBps: bigint;
};

export interface RiskGuardianInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "gov"
      | "isTradingAllowed"
      | "isVaultPaused"
      | "reportRisk"
      | "riskOracle"
      | "setVaultLimits"
      | "vaultLimits"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gov", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isTradingAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVaultPaused",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportRisk",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "riskOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultLimits",
    values: [AddressLike, RiskLimitsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultLimits",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "gov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTradingAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVaultPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reportRisk", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "riskOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVaultLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultLimits",
    data: BytesLike
  ): Result;
}

export interface RiskGuardian extends BaseContract {
  connect(runner?: ContractRunner | null): RiskGuardian;
  waitForDeployment(): Promise<this>;

  interface: RiskGuardianInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gov: TypedContractMethod<[], [string], "view">;

  isTradingAllowed: TypedContractMethod<
    [vault: AddressLike],
    [boolean],
    "view"
  >;

  isVaultPaused: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  reportRisk: TypedContractMethod<
    [
      vault: AddressLike,
      realizedDrawdownBps: BigNumberish,
      leverageBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  riskOracle: TypedContractMethod<[], [string], "view">;

  setVaultLimits: TypedContractMethod<
    [vault: AddressLike, limits: RiskLimitsStruct],
    [void],
    "nonpayable"
  >;

  vaultLimits: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        maxLeverageBps: bigint;
        maxDrawdownBps: bigint;
        maxSingleAssetExposureBps: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gov"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isTradingAllowed"
  ): TypedContractMethod<[vault: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVaultPaused"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "reportRisk"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      realizedDrawdownBps: BigNumberish,
      leverageBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "riskOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setVaultLimits"
  ): TypedContractMethod<
    [vault: AddressLike, limits: RiskLimitsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaultLimits"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        maxLeverageBps: bigint;
        maxDrawdownBps: bigint;
        maxSingleAssetExposureBps: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
