/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type StrategyMetaStruct = {
  id: BytesLike;
  classId: BigNumberish;
  enabled: boolean;
};

export type StrategyMetaStructOutput = [
  id: string,
  classId: bigint,
  enabled: boolean
] & { id: string; classId: bigint; enabled: boolean };

export interface StrategyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "gov"
      | "registerStrategy"
      | "setStrategyEnabled"
      | "strategies"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gov", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerStrategy",
    values: [StrategyMetaStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategyEnabled",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "strategies",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "gov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStrategyEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "strategies", data: BytesLike): Result;
}

export interface StrategyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyRegistry;
  waitForDeployment(): Promise<this>;

  interface: StrategyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gov: TypedContractMethod<[], [string], "view">;

  registerStrategy: TypedContractMethod<
    [meta: StrategyMetaStruct],
    [void],
    "nonpayable"
  >;

  setStrategyEnabled: TypedContractMethod<
    [id: BytesLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  strategies: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean] & {
        id: string;
        classId: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gov"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerStrategy"
  ): TypedContractMethod<[meta: StrategyMetaStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStrategyEnabled"
  ): TypedContractMethod<
    [id: BytesLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "strategies"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean] & {
        id: string;
        classId: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
